// src/icons/registry.js

// All entries point to the "-fill" variant where Bootstrap Icons has one.
// Full list of ids: node_modules/bootstrap-icons/bootstrap-icons.svg (search for -fill)
export const ICON_REGISTRY = {
  rocket: 'rocket-takeoff-fill',
  graduationCap: 'mortarboard-fill',
  shoppingBag: 'bag-fill',
  cart: 'cart-fill',
  droplet: 'droplet-fill',
  camera: 'camera-fill',
  cameraReels: 'camera-reels-fill',
  flag: 'flag-fill',
  bike: 'bicycle', // no fill variant exists for this one — kept as-is
  folder: 'folder-fill',
  folderOpen: 'folder2-open',
  star: 'star-fill',
  briefcase: 'briefcase-fill',
  code: 'code-square',
  palette: 'palette-fill',
  music: 'music-note-beamed',
  book: 'book-fill',
  bookmark: 'bookmark-fill',
  globe: 'globe-americas',
  heart: 'heart-fill',
  target: 'bullseye',
  lightning: 'lightning-charge-fill',
  house: 'house-fill',
  building: 'building-fill',
  gear: 'gear-fill',
  wrench: 'wrench-adjustable-circle-fill',
  puzzle: 'puzzle-fill',
  trophy: 'trophy-fill',
  gift: 'gift-fill',
  gem: 'gem',
  compass: 'compass-fill',
  map: 'map-fill',
  pin: 'geo-alt-fill',
  clock: 'clock-fill',
  calendar: 'calendar-fill',
  envelope: 'envelope-fill',
  chat: 'chat-fill',
  megaphone: 'megaphone-fill',
  lightbulb: 'lightbulb-fill',
  brush: 'brush-fill',
  pencil: 'pencil-fill',
  pen: 'pen-fill',
  film: 'film',
  controller: 'controller',
  headphones: 'headphones',
  mic: 'mic-fill',
  cloud: 'cloud-fill',
  sun: 'sun-fill',
  moon: 'moon-fill',
  snow: 'snow',
  fire: 'fire',
  tree: 'tree-fill',
  flower: 'flower1',
  paw: 'p-circle-fill', // bootstrap-icons has no literal "paw-fill" — swap if you find a better fit
  airplane: 'airplane-fill',
  car: 'car-front-fill',
  bus: 'bus-front-fill',
  train: 'train-front-fill',
  ship: 'ship',
  anchor: 'anchor',
  umbrella: 'umbrella-fill',
  shield: 'shield-fill',
  lock: 'lock-fill',
  key: 'key-fill',
  eye: 'eye-fill',
  bell: 'bell-fill',
  flag2: 'flag-fill',
  cup: 'cup-hot-fill',
  basket: 'basket-fill',
  bank: 'bank2',
  wallet: 'wallet-fill',
  creditCard: 'credit-card-fill',
  piggyBank: 'piggy-bank-fill',
  graph: 'graph-up-arrow',
  pieChart: 'pie-chart-fill',
  server: 'server',
  database: 'database-fill',
  cpu: 'cpu-fill',
  phone: 'phone-fill',
  laptop: 'laptop-fill',
  tv: 'tv-fill',
};

export const ICON_KEYS = Object.keys(ICON_REGISTRY);