export const language = {
    "en-US": {
        home: "Home",
        allProjects: "All Projects",
        newProject: "New Project",
        myProfile: "My profile",
        settings: "Settings",
        termsOfUse: "Terms of Use",
        logout: "Logout",
        general: "General",
        editProfile: "Edit my Profile",
        uploadWallpaper: "Upload a wallpaper",
        email: "Email",
        firstName: "First Name",
        lastName: "Last Name",
        month: "Month",
        date: "Date",
        year: "Year",
        gender: "Gender",
        male: "Male",
        female: "Female",
        preferNotToSay: "Prefer not to say",
        saveChanges: "Save Changes",
        removeProfilePicture: "Remove profile picture",
        glass: "Glass",
        light: "Light",
        dark: "Dark",
        activity: "Activity",
        personalInformation: "Personal Information",
        languageAndRegion: "Language & Region",
        appearance: "Appearance",
        notifications: "Notifications",
        extensions: "Extensions",
        commandPalette: "Command Palette",
        userGuide: "User Guide",
        privacyPolicy: "Privacy Policy",
        contactSupport: "Contact / Support",
    },
    "fr-FR": {
        home: "Accueil",
        allProjects: "Tous les projets",
        newProject: "Nouveau projet",
        myProfile: "Mon profil",
        settings: "Paramètres",
        termsOfUse: "Conditions d'utilisation",
        logout: "Déconnexion",
        general: "General",
        editProfile: "Modifier mon profil",
        uploadWallpaper: "Télécharger un fond d'écran",
        email: "E-mail",
        firstName: "Prénom",
        lastName: "Nom",
        month: "Mois",
        date: "Jour",
        year: "Année",
        gender: "Genre",
        male: "Homme",
        female: "Femme",
        preferNotToSay: "Préfère ne pas dire",
        saveChanges: "Enregistrer les modifications",
        removeProfilePicture: "Supprimer la photo de profil",
        glass: "Verre",
        light: "Clair",
        dark: "Sombre",
        activity: "Activité",
        personalInformation: "Informations personnelles",
        languageAndRegion: "Langue et région",
        appearance: "Apparence",
        notifications: "Notifications",
        extensions: "Extensions",
        commandPalette: "Palette de commandes",
        userGuide: "Guide d'utilisateur",
        privacyPolicy: "Politique de confidentialité",
        contactSupport: "Contact / Assistance",
    },
    "es-CO": {
        home: "Inicio",
        allProjects: "Proyectos",
        newProject: "Nuevo proyecto",
        myProfile: "Mi perfil",
        settings: "Configuración",
        termsOfUse: "Términos de uso",
        logout: "Cerrar sesión",
        general: "General",
        editProfile: "Editar mi perfil",
        uploadWallpaper: "Subir un fondo de pantalla",
        email: "Correo electrónico",
        firstName: "Nombre",
        lastName: "Apellido",
        month: "Mes",
        date: "Día",
        year: "Año",
        gender: "Género",
        male: "Masculino",
        female: "Femenino",
        preferNotToSay: "Prefiero no decirlo",
        saveChanges: "Guardar cambios",
        removeProfilePicture: "Eliminar foto de perfil",
        glass: "Vidrio",
        light: "Claro",
        dark: "Oscuro",
        activity: "Actividad",
        personalInformation: "Información personal",
        languageAndRegion: "Idioma y región",
        appearance: "Apariencia",
        notifications: "Notificaciones",
        extensions: "Extensiones",
        commandPalette: "Paleta de comandos",
        userGuide: "Guía del usuario",
        privacyPolicy: "Política de privacidad",
        contactSupport: "Contacto / Soporte",
    }
};