export const language = {
    "en-US": {
        home: "Home",
        allProjects: "All Projects",
        newProject: "New Project",
        myProfile: "My profile",
        settings: "Settings",
        aspect: "Aspect",
        termsOfUse: "Terms of Use",
        logout: "Logout",
        editProfile: "Edit my Profile",
        uploadWallpaper: "Upload a wallpaper",
        email: "Email",
        firstName: "First Name",
        lastName: "Last Name",
        month: "Month",
        date: "Date",
        year: "Year",
        gender: "Gender",
        male: "Male",
        female: "Female",
        preferNotToSay: "Prefer not to say",
        saveChanges: "Save Changes",
        removeProfilePicture: "Remove profile picture"
    },
    "fr-FR": {
        home: "Accueil",
        allProjects: "Tous les projets",
        newProject: "Nouveau projet",
        myProfile: "Mon profil",
        settings: "Paramètres",
        aspect: "Aspect",
        termsOfUse: "Conditions d'utilisation",
        logout: "Déconnexion",
        editProfile: "Modifier mon profil",
        uploadWallpaper: "Télécharger un fond d'écran",
        email: "E-mail",
        firstName: "Prénom",
        lastName: "Nom",
        month: "Mois",
        date: "Jour",
        year: "Année",
        gender: "Genre",
        male: "Homme",
        female: "Femme",
        preferNotToSay: "Préfère ne pas dire",
        saveChanges: "Enregistrer les modifications",
        removeProfilePicture: "Supprimer la photo de profil"
    },
    "es-CO": {
        home: "Inicio",
        allProjects: "Proyectos",
        newProject: "Nuevo proyecto",
        myProfile: "Mi perfil",
        settings: "Configuración",
        aspect: "Aspecto",
        termsOfUse: "Términos de uso",
        logout: "Cerrar sesión",
        editProfile: "Editar mi perfil",
        uploadWallpaper: "Subir un fondo de pantalla",
        email: "Correo electrónico",
        firstName: "Nombre",
        lastName: "Apellido",
        month: "Mes",
        date: "Día",
        year: "Año",
        gender: "Género",
        male: "Masculino",
        female: "Femenino",
        preferNotToSay: "Prefiero no decirlo",
        saveChanges: "Guardar cambios",
        removeProfilePicture: "Eliminar foto de perfil"
    }
};